print("==== CURICULUM VITAE ====")
print()

nama = input("Masukkan nama anda : ")
jurusan = input("Masukkan jurusan anda : ")
umur = input("Masukkan umur anda : ")
alamat = input("Masukkan alamat anda : ")
lulusan = input("Anda lulusan mana : ")
email = input(" masukkan alamat email anda : ")
facebook = input("masukkan facebook anda :  ")
instagram = input("masukkan instagram anda : ")
hobby = input(" masukkan hobby anda :")
print()

print("=="*20)
print("- Nama    : ",nama)
print("- Jurusan : ",jurusan)
print("- Umur    : ",umur)
print("- Alamat  : ",alamat)
print("- Lulusan : ",lulusan)
print("- alamat email :",email)
print("- facebook:",facebook)
print("- instagram :",instagram)
print("-hobby :",hobby)
print("=="*20)